version: '3'

services:
  front:
    build:
      context: .
      dockerfile: docker/front.Dockerfile
      args:
        - NEXT_PUBLIC_MAPBOX_TOKEN=pk.eyJ1IjoidGFwaWlyaSIsImEiOiJjbGhrZnM0NnUwcmkxM2tudWF1Zm95MHY1In0.geANXRleHX7AcKW0l4pKFg
    image: ghcr.io/tik15ryyb/approbatur-app-front
    ports:
      - 3010:3000
