version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: my-postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: approbator
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
