version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: ../docker/DataStructureService.Dockerfile
    ports:
      - "5010:5000"
    env_file:
      - "DataStructureService.env"
    depends_on:
      - db
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: my-postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: approbator
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
