name: SonarQube Scan

on:
  push:

jobs:
  sonar-scan:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonarqube
      run: sonar-scanner
           -Dsonar.sources=$GITHUB_WORKSPACE
           -Dsonar.branch.name=${GITHUB_REF##*/}
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
